### ISSUE TITLE
Doesn't seem to support subdirectories

### ISSUE THREAD

**Issue by steeeeev0** [altepizza/scripts#1]
My nextcloud instance is behind an nginx reverse proxy and uses a subdirectory like this: `domain.link/cloud`
When I use this recovery script and specify the url as requested, it comes up with an error:

````
Please enter your basic url in this exact format https://your.cloud.com: https://domain.link/cloud/
Traceback (most recent call last):
  File "recover_orphaned_bookmarks.py", line 6, in <module>
    'Please enter your basic url in this exact format https://your.cloud.com: ')
  File "<string>", line 1
    https://domain.link/cloud/
         ^
SyntaxError: invalid syntax
````
MacOS 10.15.7
Python 2.7.16
pip 20.2.4

**Comment by altepizza** [comment]
Try it without the "/" at the end. Meaning https://domain.link/cloud instead of https://domain.link/cloud/

This script is not very sophisticated. If this was the error, then I'll enhance the script in case someone else comes around.

**Comment by steeeeev0** [comment]
Same error. Omitting the last '/' does not solve the issue.

**Comment by steeeeev0** [comment]
It seems any URL I type crashes the script.

**Comment by altepizza** [comment]
Gotcha. Please use python 3.x.x instead of 2.x.x.

**Comment by steeeeev0** [comment]
Using python3 solved the issue. Thanks!
